### ISSUE TITLE
Numbers too close

### ISSUE THREAD

**Issue by ImLeonardoo** [LoneDev6/RPGhuds#37] opened 2023-07-15 10:36 UTC
![image](https://github.com/LoneDev6/RPGhuds/assets/91559829/52841b5a-d254-4a12-804b-67650615ffe6)
Client version: 1.19.4
Server version: Paper 1.19.4

**Comment by LoneDev6** [comment] 2023-07-17 08:56
Duplicate of https://github.com/LoneDev6/RPGhuds/issues/35

**Closed as not planned by LoneDev6** 2023-07-17 08:56 UTC
Labels: duplicate
