### ISSUE TITLE
Numbers are too close to each other.

### ISSUE THREAD

**Issue by D4W3-GS** [LoneDev6/RPGhuds#35] opened 2023-06-04 10:01 UTC
Hi, how can i add a "margin" to thease numbers?

![image](https://github.com/LoneDev6/RPGhuds/assets/58122301/9e02e044-c6d8-425f-a9ce-0f4122592346)

**Comment by LoneDev6** [comment] 2023-06-05 08:45
duplicate of https://github.com/LoneDev6/RPGhuds/issues/31

**Closed as not planned by LoneDev6** 2023-06-05 08:45 UTC
Labels: duplicate
